### ISSUE TITLE
discid.rb: rounding & Installation

### ISSUE THREAD

**Issue by DazBYorks** [phw/ruby-discid#14]
In **discid.rb** you round the result in _sectors_to_seconds_, which can return the wrong value when constructing a TOC string for such as XMCD (freeDB) files, see:
http://ftp.freedb.org/pub/freedb/latest/DBFORMAT
> "# Disc length: N"

> where the number of seconds in the CD's play length is substituted for "N".
> The number of seconds should be computed by dividing the total number of
> 1/75th second frames in the CD by 75 and truncating any remainder. **This number**
> **may not be rounded**.

As for the documentation, it may be worth adding a note for Windows users that the MusicBrainz **discid.dll** in the download is to be copied to the **bin** directory of the Ruby installation. Also, I gave no thought to having had installed the 64-bit version of Ruby and was thus left scratching my head when discid.dll couldn't be loaded, so it's probably worth mentioning that a 32-bit install is required.

Finally, thanks for both working on this and acting so promptly :-)

**Comment by phw** [comment]
Thanks for the report, I will look into this and update `sectors_to_seconds` accordingly.

Regarding the `discid.dll` on windows you don't need to put it into the Ruby bin folder if you don't want to. You can put it where ever Windows can find it. This can be system wide or local, see https://msdn.microsoft.com/en-us/library/windows/desktop/ms682586%28v=vs.85%29.aspx#search_order_for_desktop_applications

I usually prefer putting the DLL into my local folder for the application instead of putting DLLs in random system directories where one can easily forget about them and get strange versioning issues. You can also use 64 bit Ruby, but than you need a 64bit version of `discid.dll`. But as there is currently no official 64bit version you would have to compile it yourself (I used to provide a 64bit version, but it is outdated and the MusicBrainz server it was hosted on disappeared).

I probably should update the documentation for Windows, but as I usually don't use Windows and it is a bit of a hassle to get everything running on Windows I probably won't do that very soon.

**Comment by DazBYorks** [comment]
Thanks once again for your prompt action.
